### ISSUE TITLE
LIGHT Version of Light_LPX

### ISSUE THREAD

**Issue by Riddler76** [IQbrod/Light_LPX#1]
**Conserver :** 
CommandAuction.cs
-- Finaliser les fonctionnalités
CommandCar.cs
-- Conserver la possibilité de refuel un car
CommandLPX.cs
-- Don't touch

**Supprimer :** 

CommandSale.cs
CommandSell.cs
CommandShop.cs
CommandCost.cs
CommandKit.cs
CommandKits.cs
CommandBuy.cs
CommandBuyV.cs

**Conserver le Dump des ID dans la BDD**
DatabaseShop.cs
(option : EnableAutoDBUpdate)

Configuration.cs

**Comment by IQbrod** [comment]
Salut,
Pourquoi faire tout ca ? :x

**Comment by IQbrod** [comment]
J'entends par la que ce n'est pas mon taff, je permet juste aux gens d'utiliser son plugin, je ne compte pas l'avancer car c'est son travail. Sans son accord ou même une simple prise de contact je ne me permettrais pas de faire son travail / de prendre sa place.

Je ne suis pas paye pour le faire et je ne souhaite pas l’être tant que je ne l'aide pas officiellement a développer :)

En espérant ta compréhension.
(De plus tu es libre de reprendre mon code et d'effectuer toi même les modifications nécessaires)

Enjoy !
IQ :)

**Comment by Riddler76** [comment]
Je comprend tout à fait ton raisonnement, l'idée de lighté la version étais juste pour te rendre le travail plus simple.

Pour ce qui est du CommandAuction.cs, il a amélioré le code sur ça dernière version ;)
On laisse tombé cette demande.

Merci à toi ;)
