### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Riddler76** [IQbrod/Light_LPX#2]
Salut IQbrod,

Il y a une mise a jour a faire sur le plugin, le dev dors encore ^^ (Il est partie a l'armé)

Dis moi quand tu peux regarder ça ;)

**Comment by Riddler76** [comment]
https://github.com/uEssentials/uEssentials/compare/1.2.3.0...master

Ca devrais t'aider ;)

**Comment by IQbrod** [comment]
Salut, tu peux me dire si ca marche ? :)

**Comment by Riddler76** [comment]
Hey, désolé j'étais en vacance ! Et bien le dev a fait ca mise a jour et a mis a jour son repo ;)

J'aurais bien testé mais il faut que tu me compile le DLL
